name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run Tests
        run: pytest .

  deploy:
    needs: test  # Ensure tests pass before deploying
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEYS }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.160.177.14 << 'EOF'
          set -e  # Exit on any command failure

          echo "Checking if Docker is installed..."

          # Check if Docker is installed
          if ! command -v docker &> /dev/null
          then
            echo "Docker not found. Installing..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            echo "Docker installed successfully."
          else
            echo "Docker is already installed."
          fi

           # Ensure the 'ubuntu' user has permission to run Docker
          echo "Ensuring 'ubuntu' user has Docker permissions..."
          sudo usermod -aG docker ubuntu
          echo "Docker permissions updated."

          # Restart SSH session for changes to take effect
          echo "Applying Docker group changes..."
          exec sudo su -l ubuntu

          # Ensure the latest image is pulled
          docker pull your-dockerhub-username/fastapi-app:latest

          # Stop and remove old container if running
          docker stop fastapi-container || true
          docker rm fastapi-container || true

          # Run the new container
          docker run -d --name fastapi-container -p 8080:8000 \your-dockerhub-username/fastapi-app:latest

          EOF
