name: Pipeline Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.242.106.214 << 'EOF'
          set -e  # Exit on any command failure

          echo "Checking if Docker is installed..."

          # Check if Docker is installed
          if ! command -v docker &> /dev/null
          then
            echo "Docker not found. Installing..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            echo "Docker installed successfully."
          else
            echo "Docker is already installed."
          fi

          # Ensure the latest image is pulled
<<<<<<< HEAD
          docker pull ajayshiv/fastapi
=======
          docker pull your-dockerhub-username/fastapi-app:latest
>>>>>>> 234422843430000a42c2568480498c7d51ff688c

          # Stop and remove old container if running
          docker stop fastapi-container || true
          docker rm fastapi-container || true

          # Run the new container
          docker run -d --name fastapi-container -p 8080:8000 \
<<<<<<< HEAD
            ajayshiv/fastapi 
=======
            your-dockerhub-username/fastapi-app:latest
>>>>>>> 234422843430000a42c2568480498c7d51ff688c

          EOF
